name: fnmap
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  intl: ^0.18.1
  provider: ^6.0.5
  desktop_window: ^0.4.0
  window_manager: ^0.3.5
  menu_bar: ^0.5.3
  flutter_parsed_text: ^2.2.1
  url_launcher: ^6.1.12
  font_awesome_flutter: ^10.5.0
  ini: ^2.1.0
  path_provider: ^2.0.15
  path: ^1.8.3
  validators: ^3.0.0
  dropdown_button2: ^2.1.3
  dropdown_plus: ^0.0.9
  uuid: ^3.0.7
  xml: ^6.3.0
  google_fonts: ^5.1.0
  pluto_grid: ^7.0.2
  loading_animation_widget: ^1.2.0+4
  file_picker: ^5.3.2
  flutter_tree: ^2.0.3
  xml2json: ^6.1.0
  flutter_json_view: ^1.1.0
  split_view: ^3.2.1
  adwaita: ^1.0.1
  logger: ^1.4.0
  flutter_markdown: ^0.6.17
  package_info_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  msix: ^3.15.0

flutter:
  uses-material-design: true
  assets:
  - assets/fnmap.png

msix_config:
  display_name: fnmap
  install_certificate: true
  publisher_display_name: Kriol Technologies
  publisher: CN=Krioltech, O=Kriol Technologies
  identity_name: Krioltech.fnmap
  capabilities: internetClient,privateNetworkClientServer
  msix_version: 1.1.0.0
  logo_path: .\assets\fnmap.png
  languages: en-us
  sign_msix: true
  #output_name: fnmap-1.0.0
  output_name: fnmap-${FNMAP_STABILITY}-${FNMAP_SUBVERSION}
  architecture: x64


  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
