name: fnmap
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  flutter_neumorphic:  # ^3.2.0
      path: Flutter-Neumorphic/
  desktop_window: ^0.4.0
  window_manager: ^0.3.2
  menu_bar: ^0.5.0
  flutter_parsed_text: ^2.2.1
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.4.0
  ini: ^2.1.0
  path_provider: ^2.0.14
  path: ^1.8.2
  validators: ^3.0.0
  dropdown_button2: ^2.1.0
  dropdown_plus: ^0.0.9
  uuid: ^3.0.7
  xml: ^6.2.2
  google_fonts: ^4.0.3
  pluto_grid: ^7.0.1
  loading_animation_widget: ^1.2.0+4
  file_picker: ^5.2.9
  flutter_tree: ^2.0.3
  xml2json: ^6.1.0
  flutter_json_view: ^1.0.0
  split_view: ^3.2.1
  adwaita: ^1.0.0
  logger: ^1.3.0
  flutter_markdown: ^0.6.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
