name: fnmap # you probably want to 'snapcraft register <name>'
title:  Flutter NMap GUI
base: core22 # the base snap is the execution environment for this snap
version: '1.4'
summary: A GUI for nmap
license: GPL-2.0
compression: xz
source-code: https://github.com/gmckesey/fnmap
type: app
description: |
  fnmap is a GUI for nmap that runs and parses the output of nmap and provides
  different views of the data.
icon: assets/fnmap.png
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic

architectures:
  - build-on: [ amd64 ]

apps:
  fnmap:
    command: fnmap
    common-id: com.krioltech.fnmap
    environment:
      DBUS_SESSION_BUS_ADDRESS: $DBUS_SESSION_BUS_ADDRESS

parts:
  fnmap:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of fnmap
    build-packages:
      - pkg-config
      - libgtk-3-dev
      - liblzma-dev



    
